USE LOGIN;

DROP TABLE IF EXISTS USER CASCADE;

-- TBL_USER 테이블 생성
CREATE TABLE IF NOT EXISTS TBL_USER
(
    USER_NO              INT AUTO_INCREMENT COMMENT '사용자 번호',
    USER_ID              VARCHAR(30) NOT NULL COMMENT '사용자 아이디',
    USER_NAME            VARCHAR(30) COMMENT '사용자 이름',
    PASSWORD             VARCHAR(100) NOT NULL COMMENT '사용자 비밀번호',
    USER_ROLE            VARCHAR(50) NOT NULL COMMENT '사용자 권한',
    LOGIN_FAIL_COUNT     INT DEFAULT 0 COMMENT '로그인 실패 횟수',
    IS_ACCOUNT_LOCKED    BOOLEAN DEFAULT FALSE COMMENT '계정 잠금 여부',
    CONSTRAINT pk_category_code PRIMARY KEY (USER_NO)
    ) ENGINE=INNODB COMMENT '고객정보';

-- TBL_LOGIN_LOG 테이블 생성
CREATE TABLE IF NOT EXISTS TBL_LOGIN_LOG
(
    ID                   BIGINT AUTO_INCREMENT COMMENT '로그 ID',
    USER_ID              VARCHAR(30) NOT NULL COMMENT '사용자 아이디',
    LOGIN_TIME           DATETIME NOT NULL COMMENT '로그인 시간',
    SUCCESS              BOOLEAN NOT NULL COMMENT '성공 여부',
    IP_ADDRESS           VARCHAR(45) COMMENT 'IP 주소',
    CONSTRAINT pk_log_id PRIMARY KEY (ID)
    ) ENGINE=INNODB COMMENT '로그인 로그';

SHOW TABLES;